"""add tutorial_reads

Revision ID: e6f874a31df7
Revises: 4cb28e58cf0d
Create Date: 2026-09-28 09:39:10.790623

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6f874a31df7'
down_revision: str | Sequence[str] | None = '4cb28e58cf0d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorial_reads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tutorial_id', sa.String(length=120), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tutorial_reads_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tutorial_reads')),
    sa.UniqueConstraint('user_id', 'tutorial_id', name=op.f('uq_tutorial_reads_user_id'))
    )
    with op.batch_alter_table('tutorial_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tutorial_reads_tutorial_id'), ['tutorial_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tutorial_reads_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tutorial_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tutorial_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_tutorial_reads_tutorial_id'))

    op.drop_table('tutorial_reads')
    # ### end Alembic commands ###
